sudo: required

services:
  - docker

before_install:
  - docker build -t rklemo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rklemo/react-test npm test

after_success:
  - docker build -t rklemo/multi-client ./client
  - docker build -t rklemo/multi-nginx ./nginx
  - docker build -t rklemo/multi-server ./server
  - docker build -t rklemo/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push rklemo/multi-client
  - docker push rklemo/multi-nginx
  - docker push rklemo/multi-server
  - docker push rklemo/multi-worker
  
deploy:
 edge: true
 provider: elasticbeanstalk
 region: us-east-2
 app: multi-docker
 env: multidocker-env
 bucket_name: elasticbeanstalk-us-east-2-947183736082
 bucket_path: docker-multi
 on:
   branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY